import numpy as np
from matplotlib import pyplot as plt
from typing import List
import csv

"""
plot points that have been generated by our cpp file
as I like using matplotlib over cpp plotting libraries
"""

def plot_points(points: np.ndarray[List[float]], name: str) -> None:
    """
    Plots a set of points
    Arguments:
        points: an array of [x,y] points
    Returns: 
        None
    """
    plt.scatter(points[:,0], points[:,1], s=0.5, color='black')
    plt.savefig(f'{name}.png')
    plt.close()

def read_points(filename: str) -> np.ndarray[List[float]]:
    # Open the CSV file
    with open(filename, newline='') as csvfile:
        # Create a CSV reader
        csvreader = csv.reader(csvfile)
        # Initialize an empty list to hold the coordinates
        coordinates = []
        # Iterate through each row in the CSV file
        for row in csvreader:
            # Convert each row to a list of coordinates and append to the main list
            coordinates.append([float(row[0]), float(row[1])])
    return np.array(coordinates)

if __name__=="__main__":
    square_points = read_points("square.csv")
    triangle_points = read_points("triangle.csv")
    plot_points(square_points, "square")
    plot_points(triangle_points, "triangle")